### ISSUE TITLE
При передаче средства возникает ошибка Missing Active Authority onixred

### ISSUE THREAD

**Issue by onixred** [GolosChain/golos#253]
Использую golos.io
Хотел перевести средства 3 пользователям. Перевожу первому все хорошо,  затем сразу второму ошибка 

> Missing Active Authority onixred

![bug1_1](https://user-images.githubusercontent.com/26665874/32549653-de419256-c4bc-11e7-831b-1538121e9708.jpg)
Подробнее об ошибке
![bug3_1](https://user-images.githubusercontent.com/26665874/32549853-86cb491c-c4bd-11e7-9879-d2977f7460e4.jpg)
После чего мне нужно авторизоваться заново и каждый раз спрашивает пароль, помогает лишь открытие в новом вкладке станицы golos.io.
![bug2_1](https://user-images.githubusercontent.com/26665874/32549921-c4908410-c4bd-11e7-842e-4ec717f3a456.jpg)

```
"Error: 3010000 tx_missing_active_auth: missing required active authority?Missing Active Authority onixred?    {"id":"onixred","auth":{"weight_threshold":1,"account_auths":[],"key_auths":[["GLS5P4UAU4NeZpLAXLbEh3B7Mp5CxsMfCoPuZQoZ8vqZ7K3fvfK5H",1]]},"owner":{"weight_threshold":1,"account_auths":[],"key_auths":[["GLS5t4WNfXtWNxF9U4DPUJ9ZRVr4Y3f8TQjz17SYwGTmdxcRDYYJL",1]]}}?    th_a  transaction.cpp:149 verify_authority??    {"ops":[["transfer",{"from":"onixred","to":"alikssandra","amount":"0.723 GBG","memo":"За конкурс https://golos.io/ru--konkurs/@onixred/ezhednevnyi-konkurs-otgadai-film-multfilm-priz-80-07-11-17-1-chast"}]],"sigs":[]}?    th_a  transaction.cpp:164 verify_authority??    {"*this":{"ref_block_num":3498,"ref_block_prefix":1504780195,"expiration":"2017-11-08T10:50:30","operations":[["transfer",{"from":"onixred","to":"alikssandra","amount":"0.723 GBG","memo":"За конкурс https://golos.io/ru--konkurs/@onixred/ezhednevnyi-konkurs-otgadai-film-multfilm-priz-80-07-11-17-1-chast"}]],"extensions":[],"signatures":[]}}?    th_a  transaction.cpp:287 verify_authority??    {"trx":{"ref_block_num":3498,"ref_block_prefix":1504780195,"expiration":"2017-11-08T10:50:30","operations":[["transfer",{"from":"onixred","to":"alikssandra","amount":"0.723 GBG","memo":"За конкурс https://golos.io/ru--konkurs/@onixred/ezhednevnyi-konkurs-otgadai-film-multfilm-priz-80-07-11-17-1-chast"}]],"extensions":[],"signatures":[]}}?    th_a  database.cpp:3409 _apply_transaction??    {"trx":{"ref_block_num":3498,"ref_block_prefix":1504780195,"expiration":"2017-11-08T10:50:30","operations":[["transfer",{"from":"onixred","to":"alikssandra","amount":"0.723 GBG","memo":"За конкурс https://golos.io/ru--konkurs/@onixred/ezhednevnyi-konkurs-otgadai-film-multfilm-priz-80-07-11-17-1-chast"}]],"extensions":[],"signatures":[]}}?    th_a  database.cpp:774 push_transaction??    {"call.method":"call","call.params":[3,"broadcast_transaction_with_callback",[null,{"ref_block_num":3498,"ref_block_prefix":1504780195,"expiration":"2017-11-08T10:50:30","operations":[["transfer",{"from":"onixred","to":"alikssandra","amount":"0.723 GBG","memo":"За конкурс https://golos.io/ru--konkurs/@onixred/ezhednevnyi-konkurs-otgadai-film-multfilm-priz-80-07-11-17-1-chast"}]],"extensions":[],"signatures":[]}]]}?    th_a  websocket_api.cpp:124 on_message (see err.payload for the full error payload)?    at e.value (https://golos.io/assets/app.81b882e8f11acff5bf95.js:17:15514)?    at WebSocket.<anonymous> (https://golos.io/assets/app.81b882e8f11acff5bf95.js:17:14381)?    at WebSocket.d (https://cdn.ravenjs.com/3.17.0/raven.min.js:2:6417)
```

**Comment by Nemo1369** [comment]
@onixred Thanks for the issue. Does not seems to be a core issue, but @b1acksun, do you think it could be a tolstoy issue?

**Comment by onixred** [comment]
maybe this is a tolstoy issue

**Comment by Nemo1369** [comment]
@b1acksun
