### ISSUE TITLE
[0.17.0] [LOW_MEM] Unable to make a post

### ISSUE THREAD

**Issue by bitfag** [GolosChain/golos#458]
Unable to post comment. No matter what permllink I use, error always the same.

```
% ./test_post.py
b'{"jsonrpc": "2.0", "id": 0, "method": "call", "params": ["database_api", "get_dynamic_global_properties", []]}'
b'{"jsonrpc": "2.0", "id": 0, "method": "call", "params": ["database_api", "get_dynamic_global_properties", []]}'
b'{"jsonrpc": "2.0", "id": 0, "method": "call", "params": ["database_api", "get_dynamic_global_properties", []]}'
b'{"jsonrpc": "2.0", "id": 0, "method": "call", "params": ["database_api", "get_dynamic_global_properties", []]}'
b'{"jsonrpc": "2.0", "id": 0, "method": "call", "params": ["database_api", "get_block", [6839]]}'
b'{"jsonrpc": "2.0", "id": 0, "method": "call", "params": ["database_api", "get_accounts", [["cyberfounder"]]]}'
found wif for pubkey: GLS58g5rWYS3XFTuGDSxLVwiBiPLoAyCZgn6aB9Ueh8Hj5qwQA3r6
wif: 5JVFFWRLwz6JoP9kguuRFfytToGU6cLgBVTL9t6NB3D3BQLbUBS
b'{"jsonrpc": "2.0", "id": 0, "method": "call", "params": ["database_api", "get_dynamic_global_properties", []]}'
b'{"jsonrpc": "2.0", "id": 0, "method": "call", "params": ["database_api", "get_dynamic_global_properties", []]}'
b'{"jsonrpc": "2.0", "id": 0, "method": "call", "params": ["database_api", "get_dynamic_global_properties", []]}'
b'{"jsonrpc": "2.0", "id": 0, "method": "call", "params": ["database_api", "get_dynamic_global_properties", []]}'
b'{"jsonrpc": "2.0", "id": 0, "method": "call", "params": ["database_api", "verify_authority", [{"ref_block_num": 6838, "ref_block_prefix": 2456407234, "expiration": "2018-03-11T10:54:43", "operations": [["comment", {"parent_author": "", "parent_permlink": "", "author": "cyberfounder", "permlink": "just-test", "title": "Just test", "body": "test, ignore", "json_metadata": ""}]], "extensions": [], "signatures": ["2062a33c1f6d56af5cedada5c696b096da8c6defe48c73a6d56e54eca6e564a37f370da41421c2be9d44308babefe84aa80d97faaba65195557bd660b5c4c73a01"]}]]}'
b'{"jsonrpc": "2.0", "id": 0, "method": "call", "params": ["network_broadcast_api", "broadcast_transaction", [{"ref_block_num": 6838, "ref_block_prefix": 2456407234, "expiration": "2018-03-11T10:54:43", "operations": [["comment", {"parent_author": "", "parent_permlink": "", "author": "cyberfounder", "permlink": "just-test", "title": "Just test", "body": "test, ignore", "json_metadata": ""}]], "extensions": [], "signatures": ["2062a33c1f6d56af5cedada5c696b096da8c6defe48c73a6d56e54eca6e564a37f370da41421c2be9d44308babefe84aa80d97faaba65195557bd660b5c4c73a01"]}]]}'
Traceback (most recent call last):
  File "./test_post.py", line 55, in <module>
    main()
  File "./test_post.py", line 52, in main
    c.post(title, body, args.me)
  File "/home/vvk/devel/golos/golos-python/steem/commit.py", line 353, in post
    return self.finalizeOp(ops, author, "posting")
  File "/home/vvk/devel/golos/golos-python/steem/commit.py", line 134, in finalizeOp
    return tx.broadcast()
  File "/home/vvk/devel/golos/golos-python/steem/transactionbuilder.py", line 146, in broadcast
    raise e
  File "/home/vvk/devel/golos/golos-python/steem/transactionbuilder.py", line 144, in broadcast
    self.steemd.broadcast_transaction(self.json())
  File "/home/vvk/devel/golos/golos-python/steem/steemd.py", line 971, in broadcast_transaction
    api='network_broadcast_api')
  File "/home/vvk/devel/golos/golos-python/steembase/http_client.py", line 250, in call
    return_with_args=return_with_args)
  File "/home/vvk/devel/golos/golos-python/steembase/http_client.py", line 270, in _return
    raise RPCError(error_message)
steembase.exceptions.RPCError: Assert Exception (10)
permlink.size() > STEEMIT_MIN_PERMLINK_LENGTH && permlink.size() < STEEMIT_MAX_PERMLINK_LENGTH: Permlink is not a valid size.
```

**Comment by bitfag** [comment]
OK, figured it out. `parent_permlink` should not be empty.
