### ISSUE TITLE
broadcast_transaction() should wait for success write to the database

### ISSUE THREAD

**Issue by bitfag** [GolosChain/golos#504]
When I'm sending a transaction through `broadcast_transaction()` I'm expecting it will be broadcasted to the network. With golos 0.17 it can be just lost (probably with log message ""FATAL write lock timeout!!!"" in golosd log).

Expected behavior is send transaction to the network or return an error message. **Transaction should not be lost silently, it's ridiculous!**

Related to #499

**Comment by afalaleev** [comment]
If error happens on stage on trying to get write lock client receive error: 
![image](https://user-images.githubusercontent.com/27198658/38247259-d148bc08-376e-11e8-8d6b-5e6108bc04c8.png)

**Comment by afalaleev** [comment]
The exception from the line: https://github.com/GolosChain/chainbase/blob/0c8e4987b3923503dc5b23ae64f5d3f98085dd6f/include/chainbase/chainbase.hpp#L1221 is packed in at the following line: https://github.com/GolosChain/golos/blob/64b96ef1d820a0beefdd23ca3eb4fc1f9f43f2f4/plugins/json_rpc/plugin.cpp#L272

**Comment by afalaleev** [comment]
At the following line https://github.com/GolosChain/golos/blob/64b96ef1d820a0beefdd23ca3eb4fc1f9f43f2f4/plugins/chain/plugin.cpp#L122 exception which happens in separated thread is forwarded to called thread.

**Comment by bitfag** [comment]
Thank you for detailed explanation. I reproduced the situation and there are really exception coming from golosd. golos-piston library got it like this:

```
Traceback (most recent call last):
  File "./test_write_lock_transfer.py", line 65, in <module>
    main()
  File "./test_write_lock_transfer.py", line 61, in main
    golos.transfer(to, amount, asset, memo=memo, account=from_acc)
  File "/home/vvk/devel/golos/scripts/venv/lib/python3.6/site-packages/piston/steem.py", line 667, in transfer
    return self.finalizeOp(op, account, "active")
  File "/home/vvk/devel/golos/scripts/venv/lib/python3.6/site-packages/piston/steem.py", line 170, in finalizeOp
    return tx.broadcast()
  File "/home/vvk/devel/golos/scripts/venv/lib/python3.6/site-packages/piston/transactionbuilder.py", line 145, in broadcast
    raise e
  File "/home/vvk/devel/golos/scripts/venv/lib/python3.6/site-packages/piston/transactionbuilder.py", line 143, in broadcast
    self.steem.rpc.broadcast_transaction(self.json(), api="network_broadcast_api")
  File "/home/vvk/devel/golos/scripts/venv/lib/python3.6/site-packages/pistonapi/steemnoderpc.py", line 163, in method
    r = self.rpcexec(query)
  File "/home/vvk/devel/golos/scripts/venv/lib/python3.6/site-packages/pistonapi/steemnoderpc.py", line 139, in rpcexec
    raise exceptions.UnhandledRPCError(msg)
pistonapi.exceptions.UnhandledRPCError: Unable to acquire WRITE lock (13)
Unable to acquire WRITE lock:
```

So, my issue with lost transaction probably is not related to a write locking. Sorry for a disturbance.
